#!/bin/sh /etc/rc.common

# TODO: this is really just a placeholder for now, so that I remember the general setup in OpenWRT.

START=99
STOP=99

USE_PROCD=1
PROG=/usr/bin/socat
NAME=aoa-proxy

PORT="$1"

aoa_proxy_instance()
{
	[ "$2" = 0 ] || {
		echo "validation failed"
		return 1
	}

	[ "$enable" = "0" ] && return 1

	procd_open_instance
	procd_set_param command "$PROG"
    procd_append_param "EXEC:\"aoa-proxy --wait --forward --port $PORT\",fork"
    procd_append_param "TCP:localhost:22"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

start_service () {
	aoa_proxy_instance
}
