#!/bin/sh /etc/rc.common
 
USE_PROCD=1

start_service() {
	if [ -z "${DEVICENAME}" ]; then
		exit
	fi
	procd_open_instance "${DEVICENAME}"
  	procd_set_param command /usr/sbin/aoa-proxy \
								--port "${DEVICENAME}" \
								--connect 22 \
								--wait \
								--forward
 	procd_set_param stdout 1
  	procd_set_param stderr 1
  	procd_close_instance
}
