#!/bin/sh /etc/rc.common
 
USE_PROCD=1

start_service() {
	local dev="$1"

	if [ -z "$dev" ]; then
		exit
	fi
	procd_open_instance "$dev"
  	procd_set_param command /usr/sbin/aoa-proxy \
								--port "$dev" \
								--connect 22 \
								--wait \
								--forward
 	procd_set_param stdout 1
  	procd_set_param stderr 1
	procd_set_param respawn
	procd_set_param term_timeout 5
	procd_close_instance
}

stop_service() {
	local dev="$1"

	if [ -z "$dev" ]; then
		exit
	fi
	procd_kill_instance "$dev"
}
