#!/bin/bash
set -x
PORT="$(basename "$1")"

FIRSTCHAR=$(mktemp -p /dev/shm)

trap "rm -f ${FIRSTCHAR}" EXIT

# DEST="localhost 22"

coproc AOA {
#  nc -l 8080
  /usr/sbin/aoa-proxy \
  --port "$PORT" \
  --wait \
  --forward
}

dd bs=1 count=1 <&${AOA[0]} >${FIRSTCHAR} 2>/dev/null

if [ ! -s "${FIRSTCHAR}" ]; then
  rm -f ${FIRSTCHAR}
  exit
fi

if grep "S" ${FIRSTCHAR} ; then
  # this is probably trying to be an SSH connection.
  # forward to ssh daemon
  DEST="localhost 22"
else
  # let's forward this by default to cockpit instead
  DEST="localhost 9090"
fi

# NOTE: if we want to check for a TLS handshake, we could check for 0x22 as a first character in the connection.

nc ${DEST} < <(
  cat ${FIRSTCHAR};   \
  rm -f ${FIRSTCHAR}; \
  cat <&${AOA[0]})    \
  >&${AOA[1]}
wait $AOA_PID
