#!/bin/sh /etc/rc.common

case "${ACTION}" in
    add)
        case "${PRODUCT}" in
            18d1/2d00/* | 18d1/2d01/* | 18d1/2d04/* | 18d1/2d05/*)
                /etc/init.d/aoa-proxy-forward "${DEVICENAME}" start
                ;;
            *)
                /usr/sbin/aoa-proxy \
                    --port="${DEVICENAME}" \
                    --announce \
                    --manufacturer="aoa-proxy" \
                    --model="" \
                    --model-version="" \
                    --serial="" \
                    --url="" \
                    --description=""
                ;;
        esac
        ;;
    remove)
        /etc/init.d/aoa-proxy-forward "${DEVICENAME}" stop
        ;;
esac