#!/bin/sh


case "${ACTION}" in
    bind)
        case "${PRODUCT}" in
            18d1/2d00/* | 18d1/2d01/* | 18d1/2d04/* | 18d1/2d05/*)
                /etc/init.d/aoa-proxy-forward start "$DEVICENAME"
                ;;
            *)
                . /etc/os-release
                MANUFACTURER="aoa-proxy"
                MODEL="$(cat /tmp/sysinfo/model 2>/dev/null || echo "OpenWRT Device")"
                # MODEL="$(echo -e "${OPENWRT_DEVICE_MANUFACTURER} ${OPENWRT_DEVICE_PRODUCT}")"
                VERSION="${PRETTY_NAME}"
                SERIAL="$(uci -q get system.@system[0].hostname || echo "openwrt")"
                DESCRIPTION="""$MODEL
IP: $(ip -o route | egrep -v "(^default|dev (virbr|docker))" | sed -r 's/.* dev (\S*) .+ src (\S+) .*/\2\t\1/')
"""
                URL="https://github.com/jo-bitsch/aoa-proxy/"
                MODEL_AND_SERVICES="""$MODEL
ssh"""
                /usr/sbin/aoa-proxy \
                    --port="${DEVICENAME}" \
                    --announce \
                    --manufacturer="$MANUFACTURER" \
                    --model="$MODEL_AND_SERVICES" \
                    --model-version="$VERSION" \
                    --serial="$SERIAL" \
                    --url="https://github.com/jo-bitsch/aoa-proxy/" \
                    --description="$DESCRIPTION"
                ;;
        esac
        ;;
    unbind)
        /etc/init.d/aoa-proxy-forward stop "${DEVICENAME}"
        ;;
esac